### ISSUE TITLE
Log javascript stacktrace on fatal error (mostly android)

### ISSUE THREAD

**Issue by proProbe** [corymsmith/react-native-fabric#75] opened 2016-10-20 11:24 UTC
Hello everyone! Im currently using the library and it works quite well. Im wondering if its somehow possible to get the stacktrace of both nonfatal errors and fatal errors. I saw the article on https://medium.com/delivery-com-engineering/add-crashlytics-to-your-react-native-ios-app-69a983a9062a#.rd6eo7pfy and it seem to work quite well for IOS. Im wondering how to do this for android.

Also,
loggin nonfatal errors on Android does not separate the difference in the payload. For example:
`logException("LoginError")` and `logException("SwipeError")` would both be labeled under `Non-fatal Exception: java.lang.RuntimeException` on the dashboard.

IOS on the other hand actually would separate these two.

**Comment by corymsmith** [comment] 2016-11-19 22:03
Going to close this as its a duplicate of #2

**Closed by corymsmith** 2016-11-19 22:03 UTC
