### ISSUE TITLE
    Crashlytics.crash(); doesn't get recorded

### ISSUE THREAD

**Issue by Diamons** [corymsmith/react-native-fabric#30] opened 2016-05-08 02:24 UTC
Crashlytics.recordError() works fine, but any crash caused by Crashlytics.crash() isn't logged.

**Comment by corymsmith** [comment] 2016-05-08 02:37
You mean that is "isn't" logged?

**Comment by Diamons** [comment] 2016-05-08 03:01
Correct, fixed typo

**Comment by Diamons** [comment] 2016-05-08 03:01
.crash() does NOT log.

**Comment by corymsmith** [comment] 2016-05-09 15:29
We're you trying this on iOS or Android? And was there any error? It's calling straight through to the native library so not sure how this wouldn't work

**Comment by c-h-** [comment] 2016-05-13 01:00
Chiming in:

Just integrated, I believe I integrated correctly.

Ran on Android, app crashes (error mentions CrashTest.java or something), but nothing appears on Crashlytics dashboard.

**Comment by corymsmith** [comment] 2016-05-13 01:08
@c-h- Do you have a stack trace? Any more details would help

**Comment by c-h-** [comment] 2016-05-13 01:12
@corymsmith: App is debug signed, installed on real device. Takes ~11 seconds to crash. Perhaps 3 or 4 of those seconds could be other JS stuff going on though in the app.

![screenshot_2016-05-12-21-10-34](https://cloud.githubusercontent.com/assets/5919164/15235051/111a8794-1886-11e6-94c9-72162be23d25.png)

**Comment by corymsmith** [comment] 2016-05-13 01:24
Have you tried in release mode? I'm guessing that in dev mode React Native catches the error. I'm using this in my own app with real errors and it's working to log them to Crashlytics

**Comment by c-h-** [comment] 2016-05-13 01:54
That was the problem (at least for me). Release build crashes (App stops) and logged to dashboard.

**Comment by corymsmith** [comment] 2016-05-13 02:34
Going to close this as this has to be case. If the calls goes through to the Native crash() method (which it is) then the only reason it wouldn't log is if Crashlytics isn't configured correctly and therefore wouldn't be caused by this lib.

**Closed by corymsmith** 2016-05-13 02:34 UTC

**Comment by mahgolfa** [comment] 2018-12-16 14:09
If you aren’t seeing crashes, there are a few common issues you can check for:

*Crashes are processed in real-time after you relaunch the app post-crash; make sure you’ve relaunched your app and that it launches fully in the foreground.

*Using the Simulator to test your app? Xcode’s debugger prevents us from capturing crash reports, but if you disconnect the debugger, then we’ll be able to capture them. Note that if your device is plugged into your machine, the debugger can still get in the way. To make sure Xcode’s debugger is disconnected:
1-Launch the Simulator.
2-Hit Stop in Xcode.
3-Launch your app in the Simulator and cause a crash.
4-Hit Run in Xcode.
The crash report will show up and you can see console output indicating that the report has been sent.

*Make sure our SDK line is after all other 3rd-party SDK lines that install an exception handler. (We need to be last one called in your appDidFinishLaunchingWithOptions method.)

*It’s possible, but rare, that we are missing a dSYM to symbolicate any crash reports. There will be an alert on your dashboard if this is the case. Click through to upload the missing dSYM. Keep in mind that exceptions are not guaranteed to crash. The full code path, including code in system libraries, matters here. If you aren’t seeing the dSYM alert, you can go to your app’s settings page, and append “/mappings” to the URL to reach it, e.g. https://fabric.io/settings/apps/some_app_id/mappings
