### ISSUE TITLE
Disable on development

### ISSUE THREAD

**Issue by pesakitan22** [corymsmith/react-native-fabric#127] opened 2017-06-09 01:55 UTC
anyone figured out how to disable this plugin on development?

**Comment by arjunkomath** [comment] 2017-06-12 16:08
+1 Facing same issue :(

**Comment by kelset** [comment] 2017-06-13 12:40
It would be quite useful to have something like a tag to filter out crashes caused by the DEBUG version of the app

**Comment by dabit1** [comment] 2017-06-21 10:32
I have the same problem :/

**Comment by jaimeagudo** [comment] 2017-06-21 11:21
For android having this on your `app/build.gradle` it should work

```
  buildTypes {
        debug {
          debuggable true
          ext.enableCrashlytics = false
        }
```

**Comment by kelset** [comment] 2017-06-21 14:03
Thanks for pointing in the right direction @jaimeagudo but I don't think that is enough: by reading [in the official docs](https://docs.fabric.io/android/crashlytics/build-tools.html#disable-crashlytics-for-debug-builds), the solution you propose is only the first step.

And if you installed this lib following the "standard" [android guide](https://github.com/corymsmith/react-native-fabric#android) I don't think you can actually do step 2 :(

As far as iOS goes, there are a couple of links ([one](https://stackoverflow.com/questions/28931322/how-to-disable-crashlytics-ios-library-using-a-flag), [two](https://h4ckish.com/2015/12/16/how-to-segment-your-debug-and-release-build-data-with-crashlytics/)) which seem to suggest that a similar thing can be done, but again I think that this lib "hides" that complexity.

I think that what is required to modify is not particularly complex but, still, native side modifications of this lib, and it could not be modified by pure JS - but maybe I'm wrong, @corymsmith do you have any better idea on how this could be handled?

**Comment by JCMais** [comment] 2017-07-21 17:44
Any plans to add support for this?

**Comment by corymsmith** [comment] 2017-07-21 18:51
I have no plans to support this, I typically use different bundle ids, etc for each environment using schemes on iOS and build flavors / variants on Android.

I would gladly accept a PR for this though.

I've rarely been using this lib lately given the current projects I'm working on so any help I can get would be gladly appreciated :)

**Comment by kelset** [comment] 2017-07-21 20:05
I'll try to understand if I'd be capable of doing it, would love to see it implemented.

**Comment by dabit1** [comment] 2017-07-24 09:30
@kelset I do step 2 without problems like this:


´´´
import com.crashlytics.android.Crashlytics;
import com.crashlytics.android.core.CrashlyticsCore;
...

@Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);

    // Set up Crashlytics, disabled for debug builds
    Crashlytics crashlyticsKit = new Crashlytics.Builder()
      .core(new CrashlyticsCore.Builder().disabled(BuildConfig.DEBUG).build())
      .build();
    Fabric.with(this, crashlyticsKit);
  }
´´´

**Comment by corymsmith** [comment] 2017-07-25 16:07
@dabit1 Any chance you can do a PR to the readme around that?

**Comment by sibelius** [comment] 2017-10-04 22:36
I think we can close this

**Comment by corymsmith** [comment] 2017-10-04 23:30
Client this as I have no intention of implementing it

**Closed by corymsmith** 2017-10-04 23:30 UTC
