### ISSUE TITLE
Could not find com.crashlytics.sdk.android:crashlytics:2.5.5@aar

### ISSUE THREAD

**Issue by kelvinaliyanto** [corymsmith/react-native-fabric#13] opened 2016-03-04 01:56 UTC
The build failed and this is what the error shows. Anyone know how to solve this?

**Comment by corymsmith** [comment] 2016-03-08 23:16
Can you post a screenshot or a more detailed error message, hard to tell what the issue is

**Comment by rkostrab** [comment] 2016-03-21 11:27
Put these lines above the `dependencies` block:
```
repositories {
    maven { url 'https://maven.fabric.io/public' }
}
```

**Comment by labithiotis** [comment] 2016-03-27 16:05
Added that above dependencies and it worked and allowed me to compile but now I am getting this error on startup:
`Must Initialize fabric before using singleton()`
I have tried to follow some answers but they are not directly related to react-native.
http://stackoverflow.com/questions/26535438/how-to-initialize-crashlytics-in-fabric-io

**Comment by corymsmith** [comment] 2016-04-14 14:58
Did you end up getting this working? Going to close this as its a Fabric setup issue, can reopen if necessary

**Closed by corymsmith** 2016-04-14 14:58 UTC

**Comment by labithiotis** [comment] 2016-04-14 15:01
Nope, adding above allowed me to compile build but running js code through error above. For android I am just not using fabric atm :(

**Comment by corymsmith** [comment] 2016-04-14 16:04
@labithiotis Check out the code that @bastiRe posted on the bottom of #20, you seem to be missing a bunch of the Fabric installation steps. Did you go through installing Fabric with the Android Studio plugin?

**Comment by quadsurf** [comment] 2017-05-22 16:22
Did not work for me, when I went to copy/paste that maven snippet above the dependency block, i noticed that the maven snippet above was already pre-existing in my code, so no need to paste was necessary, which means this issue still exists even with that maven snippet.

**Comment by CharlesMangwa** [comment] 2017-10-10 12:34
To anyone dealing with this error, this comment might be really helpful: https://github.com/corymsmith/react-native-fabric/issues/10#issuecomment-249282998!

**Comment by sunny635533** [comment] 2017-10-12 02:56
@rkostrab please tell me where i should add this,
 repositories {
    maven { url 'https://maven.fabric.io/public' }
}
I tried some build.gradle,still has the error. I really don't know where.could tell me in more detail,thanks!

**Comment by macashok81** [comment] 2017-12-15 06:59
@sunny635533  You should add this to android/app/build.gradle. I was getting the same error and this fixed it.   

apply plugin: 'io.fabric'
repositories {
  maven { url 'https://maven.fabric.io/public' }
}

and compile project(':react-native-fabric') in dependencies.

**Comment by sunny635533** [comment] 2017-12-15 09:54
@macashok81 thanks. you are right!

**Comment by radjivF** [comment] 2018-08-07 03:44
hey guys,

I get ```Plugin with id 'io.fabric' not found.```

Any idea why ?

**Comment by waqas-alii** [comment] 2020-08-24 07:56
i

> hey guys,
> 
> I get `Plugin with id 'io.fabric' not found.`
> 
> Any idea why ?

same for me
