### ISSUE TITLE
Does this handle crashes in javascript?

### ISSUE THREAD

**Issue by DougBanksPersonal** [corymsmith/react-native-fabric#8] opened 2016-02-10 23:38 UTC
Hey there - 
We have a hybrid iOS app (some native code, some react native).
Crashlytics working fine for the native code part.

For RN, if there's a crash, it's just going to show up as a crash in the RN implementation code, with no insight into the actual js code/stack trace that's the root of the problem.

I saw this article:
https://medium.com/delivery-com-engineering/add-crashlytics-to-your-react-native-ios-app-69a983a9062a#.1qbqf5jsm

which attempts to address that problem through logging.

How does this library handle that issue?  If I install this, then crash in javascript, will crashlytics recognize that as a js crash and give insight into the js that caused the crash?

Thanks
Doug

**Comment by lrettig** [comment] 2016-02-11 19:34
I'm pretty sure the answer to your question is yes, you'll see the full stack trace, etc. when Crashlytics catches an error that comes from JS. But I'm not 100% sure. Happy to report back upon further testing.

Take a look also at #9

**Comment by lrettig** [comment] 2016-02-12 17:45
Confirmed. Here's what it looks like when it traps a fatal error from JS in Crashlytics.

Logs are on top, JS stack is on the bottom. It's not pretty but the data is there. I didn't include the actual iOS stack since it's not really relevant for JS errors.

![Imgur](http://i.imgur.com/7vKbF3n.png?1)

**Comment by lrettig** [comment] 2016-02-12 17:52
By the way, it looks like this stack trace comes (unsurprisingly) from the minified code. The blog post you cited above says:

> Note: If you’re minifying your JS bundle, you’ll need to generate the source map at the same directory in order to access the JS stack trace. You can do that by adding the option “ — sourcemap-output filename.map” to the react-native bundle command.

I did this but I'm not sure what effect it's supposed to have inside Crashlytics. I just commented on that post asking for clarification!

**Comment by DougBanksPersonal** [comment] 2016-02-14 22:00
Thanks for your research!

**Comment by ekryski** [comment] 2016-03-11 03:33
@corymsmith close this guy! :stuck_out_tongue:

**Closed** 2016-03-14 16:16 UTC

**Comment by rturk** [comment] 2016-03-31 19:38
I can't make it work. Do libraries or appDelegate.m need to be loaded in a particular order?

**Comment by lrettig** [comment] 2016-04-01 14:42
I don't think so. AppDelegate.m is by definition always loaded first. What error are you getting?

**Comment by rohitgoyal** [comment] 2016-12-28 15:52
> By the way, it looks like this stack trace comes (unsurprisingly) from the minified code. The blog post you cited above says:
> 
> Note: If you’re minifying your JS bundle, you’ll need to generate the source map at the same directory in order to access the JS stack trace. You can do that by adding the option “ — sourcemap-output filename.map” to the react-native bundle command.
> I did this but I'm not sure what effect it's supposed to have inside Crashlytics. I just commented on that post asking for clarification!

@lrettig Did you find any clarification on this?

**Comment by Amurmurmur** [comment] 2017-02-03 04:19
Whats the point of this lib than?

[https://github.com/mikelambert/react-native-fabric-crashlytics](https://github.com/mikelambert/react-native-fabric-crashlytics)

Isnt it suppose to redirect RN JS exception to crashlytics?

**Comment by neuberoliveira** [comment] 2017-10-20 19:40
@lrettig 

> Note: If you’re minifying your JS bundle, you’ll need to generate the source map at the same 
directory in order to access the JS stack trace. You can do that by adding the option “ — sourcemap-output filename.map” to the react-native bundle command.

where exactly i put this param ` — sourcemap-output filename.map` ?
normaly i do a release build by runing `gradlew assembleRlease`

thanks

**Comment by lrettig** [comment] 2017-10-30 20:44
@neuberoliveira You run `react-native bundle` in order to produce a bundle file for a production release. Things may have changed since this was written a year and a half ago. I don't know where gradle fits in to the process today.
