### ISSUE TITLE
Cannot read property 'crash' of undefined - on android

### ISSUE THREAD

**Issue by s2zaman** [corymsmith/react-native-fabric#87] opened 2016-12-22 10:52 UTC
I got this for android using;
`react-native-cli: 1.3.0`
`react-native: 0.38.0`
and
`"react-native-fabric": "^0.3.2"`  in package.json

![image](https://cloud.githubusercontent.com/assets/5410255/21423208/85f69f26-c85d-11e6-910a-1466249e199e.png)

Followed [this resource](https://github.com/corymsmith/react-native-fabric/issues/47#issuecomment-228043575), but still the same error
I imported the class in both ways as;
   `import Fabric, {Crashlytics} from 'react-native-fabric';`
and secondly as
   `var Fabric = require('react-native-fabric');`
   `var {Crashlytics} = Fabric;`

In both cases, it gave the same error.  :( 

trace from VS Code debugger:
```
Cannot read property 'crash' of undefined
Cannot read property 'crash' of undefined
Module AppRegistry is not a registered callable module (calling runApplication)
Unable to symbolicate stack trace: The stack is null
Unable to symbolicate stack trace: The stack is null
```

Any one came up with the solution to this, buddies !

**Comment by corymsmith** [comment] 2016-12-22 19:41
This looks like you havent properly set up the Fabric Android SDK

**Comment by s2zaman** [comment] 2016-12-26 10:11
@corymsmith 
I have followed the steps as described for **Android Without Android Studio** from here https://github.com/corymsmith/react-native-fabric

The included libraries (in MainApplication.java) are as under;
```
import com.smixx.fabric.FabricPackage;
import com.crashlytics.android.Crashlytics;
import io.fabric.sdk.android.Fabric;
```
I came across the following errors

First error (in VS-Code debugger): `error: package com.smixx.fabric does not exist`
Second error (in VS-Code debugger): `error: cannot find symbol new FabricPackage()`
Third error (on emulator, after build): `Cannot read property 'crash' of undefined`

The 'First error disappears when i remove this reference **import com.smixx.fabric.FabricPackage;**.
The 'Second error' disappears when i remove this call **new FabricPackage()**.

After removing the above errors **(i know that's not the solution 👎 )**,, the code is built successfully and a new error appears on the emulator, i-e `Cannot read property 'crash' of undefined`


My guesses: A reference to the SDK file or (its CDN url) is missing
Any clue for this issue ?

**Comment by guns2410** [comment] 2017-01-06 10:17
The error says

```
undefined is not an object (evaluating 'SMXCrashlytics.crash')

<unknown>
Crashlytics.js:11
```

which refers to 

```javascript
module.exports = {

  crash: SMXCrashlytics.crash, // this line
```

so i guess, problem with the SDK configuration

**Comment by vdlindenmark** [comment] 2017-01-13 16:27
I think i have the same error. The app crashed on Android and won't load. On iOS everything works fine.  `01-13 17:18:01.920  5610  5641 E ReactNativeJS: undefined is not an object (evaluating 's.crash')
01-13 17:18:01.932  5610  5641 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
01-13 17:18:02.043  5610  5641 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)`

**Comment by corymsmith** [comment] 2017-01-13 21:08
@vdlindenmark This means you don't have the native module registered correctly for Android.

**Comment by guns2410** [comment] 2017-01-14 05:11
That's right @corymsmith 

I figured out that while using the react-native-navigation library, the iOS version works perfect, but for android, we change MainApplication.java class to extend to `NavigationApplication` which creates a problem for `react-native-fabric`

This is how is got it working with `react-native-navigation`

```java
public class MainApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        // Add the packages you require here.
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
                new FabricPackage(),
                new VectorIconsPackage(),
                new LinearGradientPackage(),
                new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG)
        );
    }

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }

        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage()
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics());
        SoLoader.init(this, /* native exopackage */ false);
    }
}
```

Hope this helps!

**Comment by vdlindenmark** [comment] 2017-01-15 13:09
@corymsmith can you tell me how i can fix this?
I used rnpm to install and crashlytics works great, also checked the manual installation and everything was good. BUT. When i use Answers, Android don't work...

**Comment by vdlindenmark** [comment] 2017-01-15 17:32
At this moment i figured out that when i don't import react-native-fabric like this:
```
var Fabric = require('react-native-fabric');
var { Crashlytics, Answers } = Fabric;
```

With or without that, on iOS everything works fine. Without that it works also fine for Android, bit with that, i get that error... :-(

**Comment by corymsmith** [comment] 2017-01-18 21:50
@s2zaman Did you ever resolve this?

**Comment by corymsmith** [comment] 2017-01-18 21:51
@vdlindenmark Can you clarify what the problem is? Maybe post some code that works and then code that doesn't work? From what you're saying it seems like its not configured properly on Android...

**Comment by wunderkind2k1** [comment] 2017-01-30 18:56
Hi. I get the same error for ios.

```
undefined is not an object (evaluating 'SMXCrashlytics.crash')

<unknown>
Crashlytics.js:11

```

It only occurs, when running on a simulator. When I build the app in Xcode and run there (on hardware or simulator) it works.

Any Ideas?

```
package.json (excerpt):


  },
  "dependencies": {
    "native-base": "0.5.13",
    "react": "~15.3.1",
    "react-native": "0.37.0",
    "react-native-fabric": "0.3.2",
    "react-native-router-flux": "3.37.0",
    "react-native-vector-icons": "^3.0.0",
    "whatwg-fetch": "^1.0.0"
  },

```

**Comment by vdlindenmark** [comment] 2017-01-30 19:13
@wunderkind2k1 did you try to reset your simulator? ("iOS Simulator" -> "Reset Content and Settings...")


@corymsmith at this moment, for me it's fixed now.

**Comment by corymsmith** [comment] 2017-01-30 19:22
@wunderkind2k1 How did you install the Fabric SDK?

**Comment by wunderkind2k1** [comment] 2017-01-30 19:25
Hi. First I tried the 'react-native install' automatic way which didn't work. After that I started from scratch with the installation via fabric app. That way it works but only on xcode.

**Comment by corymsmith** [comment] 2017-01-30 19:27
@wunderkind2k1 Regardless of whether you do `react-native install` you should install the Fabric SDK either via their app or from CocoaPods. The install process only links this library, you still have to have Crashlytics set up in your XCode project.

**Comment by wunderkind2k1** [comment] 2017-01-30 19:34
I did the installation via their app. To say it exactly: I can see the events and logs in the fabric dashboard. But only when running on device or from XCode.

![screen shot 2017-01-30 at 20 31 23](https://cloud.githubusercontent.com/assets/552617/22438149/2883285e-e72b-11e6-8612-f3d153977362.png)

**Comment by wunderkind2k1** [comment] 2017-01-30 19:41
.. by the way: resetting the simulator didn't help either. Bummer. But I just want to say that I really appreciate your help and the work you put into this project.

**Comment by corymsmith** [comment] 2017-01-30 19:44
@wunderkind2k1 Sometimes there can be a delay for events showing up in the dashboard, I've noticed that sometimes backgrounding the app will cause events to be flushed from the queue. I believe that in DEBUG mode they may not send some / all events, can't quite recall exactly

**Comment by wunderkind2k1** [comment] 2017-01-30 19:45
Its true. The events do have a delay when the app is running. But the problem is of course the app crash in the simulator.

**Comment by wunderkind2k1** [comment] 2017-02-06 21:21
Hi. We found a **solution** today!

We had the build scheme in XCode set to Release (for deployment). This setting didn't fit well with fabric when run with react-native build tools on the simulator.

Since we switched back to the react-native default "debug" - everything works fine with the react-native and the XCode Build-Tools.

So for iOS be sure to: open your project in Xcode and select _Product → Scheme → Edit Scheme..._ (or press ⌘ + <). Next, select Run from the menu on the left and change the Build Configuration to _Debug_.

**Comment by s2zaman** [comment] 2017-02-08 14:38
Closing this issue, as the current topic is more related to this new [issue](https://github.com/corymsmith/react-native-fabric/issues/102)

**Closed** 2017-02-08 14:38 UTC
Labels: Android

**Comment by s2zaman** [comment] 2017-02-08 14:57
@corymsmith !
yupp, i solved it by following the official docs again from the start.
And secondly, from an article, i read about it that this Crash somehow encounters only when we are in Debugging mode on emulator. But once all configured, and installed on a device or emulator, it works okay 👍 !

**Comment by shreyaspadhye3011** [comment] 2018-02-23 11:15
Android - Faced same issue. Turns out I missed out on linking the library as it is not specifically mentioned anywhere on the npm page.

Executed `react-native link` and that solved the problem for me. Hope this helps somebody.
