### ISSUE TITLE
TwitterKit / login

### ISSUE THREAD

**Issue by karan** [corymsmith/react-native-fabric#1] opened 2016-01-22 23:26 UTC
Hey great work here. I was wondering if you had plan to add TwitterKit or login with Twitter in this, or if you are open to PR's.

**Comment by corymsmith** [comment] 2016-01-22 23:29
I have that in my todo list and had started a little bit of it but wanted to get this out first. I'm definitely open to PR's :)

**Comment by corymsmith** [comment] 2016-01-23 00:09
@karan Are you mainly looking for login / logout? Or anything specifically? I can check in what I have so far. I have simple login / logout for both iOS / Android

**Comment by corymsmith** [comment] 2016-01-23 02:22
@karan I've added login / logout to the twitterkit-support branch https://github.com/corymsmith/react-native-fabric/tree/twitterkit-support

There's a few extra steps to getting set up that I have to document in the readme to handle onActivityResult in Android, etc.

**Comment by karan** [comment] 2016-01-23 04:00
@corymsmith yeah just the login/logout. Trying to learn RN so I think this is helpful. Thanks buddy.

**Comment by corymsmith** [comment] 2016-01-23 04:05
@karan No problem! If you have any other questions about RN hit me up on Twitter, username is Smixx

**Comment by karan** [comment] 2016-01-23 21:41
@corymsmith Have you tested the code? I'm wondering where the config for the module is. (Application key and secret)

**Comment by corymsmith** [comment] 2016-01-23 21:46
That's part of the setup instructions I have to include. Basically the way it is now you set up Fabric in your app the same way you typically would so your Application Key and Secret are in your .plist file for iOS and on Android in the manifest file

**Comment by karan** [comment] 2016-01-23 22:16
Weird. Because my `MainActivity` doesn't have an `onCreate` function. I'm trying to add Fabric using Android Studio nevertheless. Let's see how that goes.

**Comment by corymsmith** [comment] 2016-01-23 22:30
@karan are you adding RN to an existing Android app? If you use "react-native init" to create your project then it sets up the MainActivity appropriately

**Comment by karan** [comment] 2016-01-23 22:33
Yeah I used `react-native init`. This is my MainActivity:

```java
package com.mobile;

import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "mobile";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage());
    }
}
```

And so installing Fabric didn't really work for me.

**Comment by corymsmith** [comment] 2016-01-23 22:39
Ahh, they must have changed how things work in the latest version of RN: 

Here's my MainActivity, I was incorrect, the API key / secret are set up in MainActivity. Here's what mine looks like with the older version of RN: https://gist.github.com/corymsmith/2ea0b3c3e2f3c59a551c

**Comment by corymsmith** [comment] 2016-01-23 22:42
You probably want something like this: 

```java
package com.mobile;

import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    // Note: Your consumer key and secret should be obfuscated in your source code before shipping.
    private static final String TWITTER_KEY = "TWITTER_KEY";
    private static final String TWITTER_SECRET = "TWITTER_SECRET";    
    
   // declare package
    private FabricPackage mFabricPackage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);

        final Fabric fabric = new Fabric.Builder(this)
                .kits(new Crashlytics(), new Twitter(authConfig))
                .build();

        Fabric.with(fabric);

        mFabricPackage = new FabricPackage(this);
    }

     // handle onActivityResult
    @Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        mFabricPackage.handleActivityResult(requestCode, resultCode, data);
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "mobile";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage());
    }
}
```

**Comment by corymsmith** [comment] 2016-01-23 22:43
Overriding onCreate and onActivityResult

**Comment by karan** [comment] 2016-01-23 22:44
My versions:

```react-native-cli: 0.1.10
react-native: 0.18.1
```

What are you on?

I just setup a new project to see if I can get Fabric working there.

**Comment by corymsmith** [comment] 2016-01-23 22:50
I'm on 0.18.1 but the project that I'm testing with was created using an earlier version of the CLI

**Comment by karan** [comment] 2016-01-23 23:36
Alright I got the thing to install and build. The Fabric docs are way off.

Now, does this usage seem fine to you? Because I get "can't read property login of undefined." (I have the twitterkit branch in `node_modules`

```js
var Fabric = require('react-native-fabric');
var Fabric = require('react-native-fabric');

...
...

Twitter.login(function(res) {
   console.log(res);
});
```

**Comment by corymsmith** [comment] 2016-01-24 00:17
In the code sample I posted I forgot to add the Fabric package to the list of available packages. You'll have to update getPackages() to add mFabricPackage to the array after MainReactPackage

**Comment by karan** [comment] 2016-01-24 00:30
That's not it. I am adding `mFabricPackage` in the function. But same error.

**Comment by karan** [comment] 2016-01-24 21:33
Ok so this isn't just a Twitter module issue. It's happening in all of them. Can't call `Crashlytics.log` -> `Cannot read property of undefined` enough though if I log the object, it's not undefined.
![image](https://cloud.githubusercontent.com/assets/3261985/12539070/17a86e1a-c29f-11e5-888a-c9ab70d0e118.png)

**Comment by corymsmith** [comment] 2016-01-24 21:57
Somehow the native modules aren't being loaded, not sure why though. Not at home at the moment is can't help until later today / tomorrow unfortunately

**Comment by corymsmith** [comment] 2016-01-24 21:57
Also, my js wraps the log call so the function is there but the native module that it calls is undefined

**Comment by karan** [comment] 2016-01-26 03:44
Hey @corymsmith any chance you were able to repro this?

**Comment by corymsmith** [comment] 2016-01-26 04:30
Can you send me the code from your main activity?

**Comment by karan** [comment] 2016-01-26 04:31
@corymsmith here you go

```java
package com.canaar;

import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import io.fabric.sdk.android.Fabric;
import com.twitter.sdk.android.Twitter;
import com.twitter.sdk.android.core.TwitterAuthConfig;
import com.smixx.fabric.FabricPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    // Note: Your consumer key and secret should be obfuscated in your source code before shipping.
    private static final String TWITTER_KEY = "AQn0NRKYcqiVBHsWbXJdZa16F";
    private static final String TWITTER_SECRET = "tLAVf6tPKfpt4PTSdxeynxuyumEOgzHK0WSmbO5d1aWwoIWwKB";

    private FabricPackage mFabricPackage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);

        final Fabric fabric = new Fabric.Builder(this)
                .kits(new Twitter(authConfig))
                .build();

        Fabric.with(fabric);

        mFabricPackage = new FabricPackage(this);
    }

    // handle onActivityResult
    @Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        mFabricPackage.handleActivityResult(requestCode, resultCode, data);
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "canaar";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        mFabricPackage,
      );
    }
}
```

**Comment by corymsmith** [comment] 2016-01-26 04:44
@karan And whats in your build.gradle? Assuming thats where Fabric added some entries.

**Comment by karan** [comment] 2016-01-26 04:47
@corymsmith so Fabric instructions were out of date.

`android/app/build.gradle`

```
apply plugin: "com.android.application"
apply plugin: 'io.fabric'  <-- I added this

import com.android.build.OutputFile

/**
 * The react.gradle file registers two tasks: bundleDebugJsAndAssets and bundleReleaseJsAndAssets.
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"]
 * ]
 */

apply from: "react.gradle"

/**
 * Set this to true to create three separate APKs instead of one:
 *   - A universal APK that works on all devices
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.canaar"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            enable enableSeparateBuildPerCPUArchitecture
            universalApk true
            reset()
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:0.18.+"
    compile project(':react-native-fabric')
    compile('com.twitter.sdk.android:twitter:1.12.0@aar') {
        transitive = true;
    }
}
```

`android/build.gradle`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'io.fabric.tools:gradle:1.+'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
}

```

**Comment by corymsmith** [comment] 2016-01-26 05:07
@karan I can't seem to reproduce it at all, really confusing

**Comment by karan** [comment] 2016-01-26 05:09
@corymsmith Uhh.. Are you on the same versions as me?

Or am I calling the fn incorrectly?

```js

var Fabric = require('react-native-fabric');

var { Twitter } = Fabric;

...
<Button style={{color: 'white'}} onPress={this.login.bind(this)}>Login with Twitter</Button>
...

login() {
    Twitter.login(function(res) {
      console.log(res);
      this.props.navigator.push({
        id: 'LoggedIn',
      });
    });
  }

```

**Comment by corymsmith** [comment] 2016-01-26 05:45
I'm not binding this.login in my code, which is strange that mine even works, but it looks more like what i have below. The callback to Login takes 2 arguments. Are you still getting the same error about it being undefined though? If so these changes shouldn't fix it...

```js

var Fabric = require('react-native-fabric');

var { Twitter } = Fabric;

...
<Button style={{color: 'white'}} onPress={this.login}>Login with Twitter</Button>
...

login() {
    Twitter.login(function(err, res) {
      console.log(res);
      this.props.navigator.push({
        id: 'LoggedIn',
      });
    });
  }
```

**Comment by corymsmith** [comment] 2016-01-26 05:47
@karan Also, can you log out React.NativeModules?

**Comment by karan** [comment] 2016-01-26 05:58
As expected, removing the binding didn't fix it. If I log React.NativeModules:

![image](https://cloud.githubusercontent.com/assets/3261985/12573481/8a09b04e-c3ae-11e5-92ab-3752ed3f7899.png)

`NativeModules` is undefined in your module's `Twitter.js`, `Crashlytics.js` and `Answers.js`. So there's something wrong before you export the modules there.

Do you mind pushing you test app that seems to work (with `node_modules`)? I can try to run that to see if it's something wrong with my system?

**Comment by corymsmith** [comment] 2016-01-26 06:08
Can you post your settings.gradle? I can't share the app now as I have to sign off for the evening, can have a peek in the AM though. Are you sure that NativeModules is undefined there and not just NativeModules.SMXCrashlytics, etc?

**Comment by karan** [comment] 2016-01-26 06:09
Ah you're right. `NativeModules.SMXCrashlytics` etc is undefined.

```
// settings.gladle

rootProject.name = 'canaar'

include ':app'

include ':react-native-fabric'
project(':react-native-fabric').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fabric/android')
```

I really appreciate you helping out here. I know how frustrating it is when software doesn't work.

**Comment by corymsmith** [comment] 2016-01-26 06:13
The issue is that the native module isn't registering, which is taken care of by the addition of mFabricPackage to the array returned in getPackages() in MainActivity. 

Everything you've shared looks 100% correct, if you want to send over the project you're testing out I can try to repro and see if I spot anything tomorrow (assuming its not sensitive or secret :) )

**Comment by karan** [comment] 2016-01-27 00:39
It's kinda confidential. If you can merge the branch into master, I can try using the component from scratch in a new project.

**Comment by corymsmith** [comment] 2016-01-27 17:23
You can always use the git URL with a specific branch in it: 

`"react-native-fabric" : "corymsmith/react-native-fabric#twitterkit-support"`

I don't want to push it to master until a bunch of issues are sorted and worked through.

**Comment by karthickvkumar** [comment] 2016-04-21 09:55
Hi @corymsmith, Thanks for this awesome library. It would be more helpful, if you update the Twitter install instructions.

Thanks in Advance

**Comment by corymsmith** [comment] 2016-04-21 13:33
@karthickvkumar Feel free to submit a PR if you have something in mind :)

**Comment by karthickvkumar** [comment] 2016-04-22 05:42
@corymsmith Im new to react-native, I tried twitter login using the twitterkit-support branch [https://github.com/corymsmith/react-native-fabric/tree/twitterkit-support](url) I followed through your steps, But it showing error in the app.

![screenshot_2016-04-22-11-06-00](https://cloud.githubusercontent.com/assets/11032434/14732749/1e30b086-087b-11e6-8d27-b0f6341ee2c4.png)

**Comment by karthickvkumar** [comment] 2016-04-22 05:54
There are the changes i have done in my app(added in image format)

**1.package.json**
![selection_011](https://cloud.githubusercontent.com/assets/11032434/14732875/1ec24e64-087c-11e6-9937-579c4754be85.png)

**2.settings.gradle**
![selection_012](https://cloud.githubusercontent.com/assets/11032434/14732888/343df0cc-087c-11e6-8161-a5638d0aaed1.png)

**3.android/build.gradle**
![selection_013](https://cloud.githubusercontent.com/assets/11032434/14732901/4c313504-087c-11e6-8c02-5c590f11e4fc.png)

**4.android/app/build.gradle**
![selection_014](https://cloud.githubusercontent.com/assets/11032434/14732912/673d2b96-087c-11e6-9691-1564a393abb0.png)
![selection_015](https://cloud.githubusercontent.com/assets/11032434/14732916/6e65bcda-087c-11e6-89b0-ced073c05460.png)

**5.MainActivity.java**
![selection_017](https://cloud.githubusercontent.com/assets/11032434/14732929/83740e88-087c-11e6-9299-d86dcd4890da.png)
![selection_018](https://cloud.githubusercontent.com/assets/11032434/14732934/8a5ef15e-087c-11e6-8dbf-fdfc2047ae0c.png)

**6.AndroidManifest.xml**
![selection_016](https://cloud.githubusercontent.com/assets/11032434/14732947/a8f9c0d0-087c-11e6-91c6-ea5d286cc265.png)


Theres are the changes i did but when i run the android app it showing the above mention error. I need your help @corymsmith 

Thanks in Advance

**Comment by corymsmith** [comment] 2016-04-23 17:30
@karthickvkumar I'm not sure what the issue is, it may be an issue with the latest version of RN?

**Comment by karthickvkumar** [comment] 2016-04-25 03:53
@corymsmith Is it working for RN 0.18?

**Comment by ramilushev** [comment] 2016-04-27 12:47
@karthickvkumar Had the same issue. FIxed by moving this line `mFabricPackage = new FabricPackage(this);` from `onCreate` to the beginning of `getPackages`.

Twitter login works fine. I also added support for composing tweets. Will do a pull request if you're interested.

**Comment by karthickvkumar** [comment] 2016-04-28 03:46
@ramilushev Thank you very much. I got struck in this problem for a long time! It would very helpful if your submit a Pull Request.
Anticipating your PR @ramilushev

**Comment by karthickvkumar** [comment] 2016-05-12 05:35
@corymsmith  @ramilushev Im getting a null pointer exception, if i use [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) in my app
> 'void com.twitter.sdk.android.core.identity.TwitterLoginButton.onActivityResult(int, int, android.content.Intent)'
I herewith attached my stack trace 
![c5bde1a2-1780-11e6-88eb-4a684ad2a910](https://cloud.githubusercontent.com/assets/11032434/15204988/5b7992ee-1831-11e6-995d-538b5f36b1e0.png)

Thanks in Advance

**Comment by ramilushev** [comment] 2016-05-12 08:01
@karthickvkumar Please create a new issue and include your MainActivity.java contents.

**Comment by karthickvkumar** [comment] 2016-05-23 14:31
@ramilushev @corymsmith Is it possible to get twitter user **profile image**, **name**, **gender**, **age**, **location**. If possible please prove any way to implement 

Thanks in Advance

**Comment by corymsmith** [comment] 2016-05-28 22:57
@karthickvkumar Things like age and gender aren't available via the Twitter API. Profile image, name and location are available via https://api.twitter.com/1.1/users/show.json. 

TwitterKit / TwitterCore has a loadUserWithID function that returns a small subset of whats returned from the API's /users/show.json.

Here's what loadUserWithID returns: 

userID
name
screenName
isVerified
isProtected
profileImageURL
profileImageMiniURL
profileImageLargeURL
formattedScreenName
profileURL

I started adding a fetchProfile function which fetches the users profile via the /users/show.json endpoint. I just checked it in and pushed to this branch and also merged in from master.

I got it successfully working on iOS but was running into some issues on Android that may be just issues with my example app's setup, I don't currently have time to investigate more at this point so a PR would be great.

**Comment by karthickvkumar** [comment] 2016-06-23 04:35
Thanks @corymsmith

**Comment by tkporter** [comment] 2016-07-27 18:32
@corymsmith It seems like this branch is pretty behind-- I'm going to bring everything up to speed, implement onActivityResult(), iOS composeTweet(), etc

Any interest in potentially merging that with master if everything looks good? I want to make sure it keeps up to date with new updates to master as well. Thanks!

**Comment by tkporter** [comment] 2016-08-07 07:30
Check out [this modular repo](https://github.com/tkporter/react-native-fabric-twitterkit) if you want to make sure twitterkit support stays up to date with master react-native-fabric

**Comment by corymsmith** [comment] 2016-08-20 18:52
Going to close this, if you need TwitterKit just use what @tkporter has created

**Closed by corymsmith** 2016-08-20 18:52 UTC
Labels: enhancement, help wanted
